import java.util.Scanner;
import java.util.Random;
class Game {
    public int randomNumber;
    public int userNumber;
    public int numberOfGuesses = 0;

    // Constructor to generate Random number within 50 numbers
    Game() {
        Random r = new Random();
        randomNumber = r.nextInt(50);
    }

    // Method to take user input
    void userInput() {
        System.out.println("Attempt Number : "+numberOfGuesses);
        System.out.println("Please Guess the number\n");
        Scanner scannerObj = new Scanner(System.in);
        userNumber = scannerObj.nextInt();
    }

    // Method to check whether the random number and number entered by user is same
    boolean check() {
        numberOfGuesses++;
        if(numberOfGuesses > 10) {
            System.out.println("You have exceeded 10 number of Attempts");
            return true;
        }
        userInput();
        if(userNumber == randomNumber) {
            System.out.println("Congratulations !!! You guessed it right in "+numberOfGuesses+" attempts\n");
            return true;
        }
        else if(userNumber > randomNumber) {
            System.out.println("it's too large ! please try again\n");
            return false;
        }
        else if(userNumber < randomNumber) {
            System.out.println("it's too low ! please try again\n");
            return false;
        }
        else {
            System.out.println("Please enter valid input");
        }
        return false;
    }
}

// Driver class(Main class)
class NumberGame {
    public static void main(String[] args) {

        Game game = new Game();
        System.out.println("Welcome to the Guess the Number game\n");
        System.out.println("You have 10 number of Attempts to guess the number generated by computer It is between 0 to 50\n");
        boolean b = false;
        while(!b) {
            b = game.check();
        }
    }
}
